version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "9999:9999"
    depends_on:
      - db

  db:
    build:
      context: ./db
    ports:
      - "3000:3000"
