apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: db-role
  namespace: default
rules:
  - apiGroups: [""]
    resources:
      [
        "pods",
        "configmaps",
        "secrets",
        "persistentvolumes",
        "persistentvolumeclaims",
        "deployments",
        "services",
        "networkpolicies",
      ]
    verbs: ["get", "list", "watch"]
