apiVersion: v1
kind: ServiceAccount
metadata:
  name: server-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: server-role
  namespace: default
rules:
  - apiGroups: [""]
    resources:
      [
        "pods",
        "deployments",
        "services",
        "networkpolicies",
      ]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: server-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: server-sa
    namespace: default
roleRef:
  kind: Role
  name: server-role
  apiGroup: rbac.authorization.k8s.io
